### PR TITLE
add change directory

### PR DESCRIPTION
**Pull request by 8HoLoN**
move into orbital directory after : `git clone https://github.com/AlexAltea/orbital`
and before  : `git submodule update --init`

### CODE REVIEW

**Comment by AlexAltea** [comment]
It's true that the instructions omit that step, but probably it would be nicer to just replace the entire snippet with only the following line:
```bash
git clone -recursive https://github.com/AlexAltea/orbital
```

**Comment by 8HoLoN** [comment]
Absolutely, and I would say even : 
`git clone --recurse-submodules -j8 https://github.com/AlexAltea/orbital`
I have updated the PR.

**Comment by ElectrodeYT** [comment]
I myself would change the `-j8` to `-jx`, as there are people that simply copy-and-paste code like this.

**Comment by AlexAltea** [comment]
Typically `-j$(nproc)` is used for *make*, though I'm not sure if it makes sense to do the same here. Still, it's probably better than hardcoding a specific value (`-j8`) or adding something that requires user editing (`-jx`).

**Comment by AlexAltea** [comment]
This repository has no submodules anymore.

**Pull request closed without merging**
