### PR TITLE
Correct & add some other syscalls

### PR DESCRIPTION
**Pull request by greggameplayer**
these changes has been made according to : 
http://www.psdevwiki.com/ps4/Syscalls

### CODE REVIEW

**Comment by AlexAltea** [comment]
Can you please squash these two commits into a single one? Just to avoid polluting the history too much with redundant messages.

**Comment by greggameplayer** [comment]
how to squash them because i can't merge them but you you can squash it and merge it at the same time because you have the write access.

**Comment by hcorion** [comment]
https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by greggameplayer** [comment]
ok i've squash them

**Comment by greggameplayer** [comment]
ok so i think it's good

**Pull request closed without merging**
